name: fitness_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pocketbase: ^0.24.0
  flutter_riverpod: ^3.3.1
  flutter_bloc: ^9.1.0
  bloc: ^9.1.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^8.0.3
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  mobile_scanner: ^7.2.0
  pedometer: ^4.0.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.5
  http: ^1.2.2
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.0
  fl_chart: ^0.71.0
  intl: ^0.20.2
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true